databases:
  - name: contactForm
    databaseName: contactForm
    user: contactForm

services:
  - type: web
    name: contactForm
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn contactForm.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: contactForm
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4